DROP TABLE registros_sisob;
CREATE TABLE registros_sisob (

    livro_num VARCHAR(6),
	folha_num VARCHAR(5),
	termo_num VARCHAR(10),
     data_lavratura DATE,
     beneficio_num BIGINT(10),
     nome_falecido VARCHAR(76),
     nome_mae VARCHAR(32),
      DN_SISOBI INT(8),
      DO_SISOBI DATE,
      cpf VARCHAR(13),
      NIT BIGINT,
	  Tipo_id_cartorio INT(1),
	  cartorio_id BIGINT(14),      
      DN_SISOBI_Ajustada VARCHAR(10),    
      ANO_OBITO INT(4),
      MES_OBITO INT(2),
      DO_SISOBI_Ajustada VARCHAR(10),
      Nome_Arquivo_Importado VARCHAR(255),
      PRIMARY KEY (nome_falecido,nome_mae,MES_OBITO)
);


DROP TABLE NG39_registros;
CREATE TABLE NG39_registros (
    id int auto_increment,
    chave VARCHAR(15),
    tipovinc_ajustado VARCHAR(25),
    ref_folha TIMESTAMP,
    num_folha INT(2),
    tipovinc VARCHAR(20),
    nomeorgao VARCHAR(100),
    municipio VARCHAR(70),
    unidade INT(7),
    desc_unid VARCHAR(60),
    numfunc INT(7),
    numvinc INT(2),
    numpens INT,
    nome VARCHAR(255),
	cpf  VARCHAR(13) ,
    categoria VARCHAR(70),
    desc_cargo VARCHAR(255),
    desc_funcao VARCHAR(255),
    especialidade VARCHAR(80),
    referencia VARCHAR(8),
    jornada VARCHAR(3),
    DTEXERC DATE,
    DTVAC DATE,
    DTAPOSENT DATE,
    DTNASC DATE,
    DTNASC_AJUSTADA DATE,
    idade INT(3),
    faixa_idade VARCHAR(250),
    vl_bruto DECIMAL(13,4),
	faixa_remuneracao_bruta VARCHAR(255),
    vldesc DECIMAL(13,4),
    subsidio DECIMAL(13,4),
    tipoevento VARCHAR(255),
    formaprov VARCHAR(30),
    VALOR_AUX1 DECIMAL(13,4),
    VALOR_AUX2 DECIMAL(13,4),
    FLEX_CAMPO_01_sexo VARCHAR(2),   
    Nome_Arquivo_importado VARCHAR(255),
    PRIMARY KEY (id)
);