/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.claytonpereira.view;

/**
 *
 * @author claytonpereira
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        setSize(800,600);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuBar = new javax.swing.JMenuBar();
        Menu_Arquivo = new javax.swing.JMenu();
        Menu_sair = new javax.swing.JMenuItem();
        Menu_importacao = new javax.swing.JMenu();
        Menu_importar_sisob = new javax.swing.JMenuItem();
        Registros = new javax.swing.JMenu();
        Menu_conta_reg_sisob = new javax.swing.JMenuItem();
        Menu_sisob_eturmalina = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu3.setText("jMenu3");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu_Arquivo.setMnemonic('f');
        Menu_Arquivo.setText("Arquivo");

        Menu_sair.setMnemonic('x');
        Menu_sair.setText("Sair");
        Menu_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_sairActionPerformed(evt);
            }
        });
        Menu_Arquivo.add(Menu_sair);

        menuBar.add(Menu_Arquivo);

        Menu_importacao.setText("Importação");

        Menu_importar_sisob.setText("Importar arquivo Sisob Mensal");
        Menu_importar_sisob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_importar_sisobActionPerformed(evt);
            }
        });
        Menu_importar_sisob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Menu_importar_sisobKeyPressed(evt);
            }
        });
        Menu_importacao.add(Menu_importar_sisob);

        menuBar.add(Menu_importacao);

        Registros.setText("Relatórios");

        Menu_conta_reg_sisob.setText("Quantidade  Reg Sisob");
        Menu_conta_reg_sisob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_conta_reg_sisobActionPerformed(evt);
            }
        });
        Registros.add(Menu_conta_reg_sisob);

        Menu_sisob_eturmalina.setText("Sisob x E-TURMALINA");
        Menu_sisob_eturmalina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_sisob_eturmalinaActionPerformed(evt);
            }
        });
        Registros.add(Menu_sisob_eturmalina);

        menuBar.add(Registros);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Menu_sairActionPerformed

    private void Menu_importar_sisobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Menu_importar_sisobKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_importar_sisobKeyPressed

    private void Menu_importar_sisobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_importar_sisobActionPerformed
        // TODO add your handling code here:
        TelaImportacaoSisobMensal sisob_mensal =  new TelaImportacaoSisobMensal();
        sisob_mensal.setVisible(true);
    }//GEN-LAST:event_Menu_importar_sisobActionPerformed

    private void Menu_conta_reg_sisobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_conta_reg_sisobActionPerformed
        // TODO add your handling code here:
          TelaSisobCount sisob_count =  new TelaSisobCount();
          sisob_count.setVisible(true);
    }//GEN-LAST:event_Menu_conta_reg_sisobActionPerformed

    private void Menu_sisob_eturmalinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_sisob_eturmalinaActionPerformed
        // TODO add your handling code here:
         TelaComparaSisobEturmalina sisob_Eturmalina =  new TelaComparaSisobEturmalina();
          sisob_Eturmalina.setVisible(true);
    }//GEN-LAST:event_Menu_sisob_eturmalinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_Arquivo;
    private javax.swing.JMenuItem Menu_conta_reg_sisob;
    private javax.swing.JMenu Menu_importacao;
    private javax.swing.JMenuItem Menu_importar_sisob;
    private javax.swing.JMenuItem Menu_sair;
    private javax.swing.JMenuItem Menu_sisob_eturmalina;
    private javax.swing.JMenu Registros;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
