/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.claytonpereira.view;

import com.claytonpereira.model.Arquivo_txt;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author claytonpereira
 */
public class TelaImportacaoSisobMensal extends javax.swing.JFrame {

    /**
     * Creates new form TelaImportacaoSisobMensal
     */
    public TelaImportacaoSisobMensal() {
        initComponents();
        setSize(800, 600);
        salve_csv_to_db.setVisible(false);
        Converte_txt_to_csv.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Converte_txt_to_csv = new javax.swing.JLabel();
        salve_csv_to_db = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setText("Converter TXT para CSV");
        jButton1.setToolTipText("O arquivo no formato = OBI + Ano com quatro digitos + mês com dois digitos exemplo: arquivo de janeiro de 2019, ficaria assim OBI201901 . ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(30, 60, 280, 23);

        jButton2.setText("Salvar Arquivo CSV no Banco");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(30, 100, 280, 23);

        Converte_txt_to_csv.setText("jLabel1");
        add(Converte_txt_to_csv);
        Converte_txt_to_csv.setBounds(350, 70, 34, 14);

        salve_csv_to_db.setText("jLabel2");
        add(salve_csv_to_db);
        salve_csv_to_db.setBounds(350, 110, 34, 14);
    }// </editor-fold>//GEN-END:initComponents

     public File seleciona_arquivo( java.awt.Component tela,String desc_tipo_arquivo, String extensao) throws FileNotFoundException{
    File arquivo = null;
    int i;
    
    
           
        JFileChooser selecionaarquivo = new JFileChooser();
        selecionaarquivo.setDialogTitle("Selecione o arquivo txt do SISOB !");
        FileFilter filter = new FileNameExtensionFilter(desc_tipo_arquivo, extensao);
        selecionaarquivo.addChoosableFileFilter(filter);  
        selecionaarquivo.setAcceptAllFileFilterUsed(false);
      
        
        
        int returnVal = selecionaarquivo.showOpenDialog(tela);
        if (returnVal == JFileChooser.APPROVE_OPTION){
          arquivo = selecionaarquivo.getSelectedFile();
          System.out.println("abrindo: " + arquivo.getName());
        }
        
        
        if(returnVal == JFileChooser.CANCEL_OPTION){
            JOptionPane.showMessageDialog(tela, "Nenhum arquivo selecionado !");
        
        }
        
        
        
        return arquivo;
    }
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     File arquivo = null ;
        try {
            arquivo = seleciona_arquivo(this,"arquivo Texto", "txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaImportacaoSisobMensal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
           Arquivo_txt txt = new Arquivo_txt();
        try {
          
          
            txt.salvar_arquivo_txt_to_csv(arquivo,"Escolha o arquivo Csv");
        } catch (IOException ex) {
            Logger.getLogger(TelaImportacaoSisobMensal.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        File arquivo = null ;
      
        try {
            arquivo = seleciona_arquivo(this,"Arquivo CSV", "csv");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaImportacaoSisobMensal.class.getName()).log(Level.SEVERE, null, ex);
        }
        Arquivo_txt texto = new Arquivo_txt();
        try {
            texto.export_csv_to_db(arquivo);
        } catch (SQLException ex) {
            Logger.getLogger(TelaImportacaoSisobMensal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaImportacaoSisobMensal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Converte_txt_to_csv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel salve_csv_to_db;
    // End of variables declaration//GEN-END:variables
}
