/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.claytonpereira.view;

import com.claytonpereira.model.DatabaseConnectionMysql;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import rst.pdfbox.layout.elements.Document;
import rst.pdfbox.layout.elements.Paragraph;
import rst.pdfbox.layout.text.Constants;

/**
 *
 * @author claytonpereira
 */
public class TelaComparaSisobEturmalina extends javax.swing.JFrame {

    /**
     * Creates new form TelaComparaSisobEturmalina
     */
    public TelaComparaSisobEturmalina() {
 
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SpinnerModel model =
        new SpinnerNumberModel(1, 1, 12, 1) ;
        SPINNER_MES = new javax.swing.JSpinner(model);
        SpinnerModel model2 =
        new SpinnerNumberModel(2019, 1994, 2050, 1) ;
        SPINNER_ANO = new javax.swing.JSpinner(model2);
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(SPINNER_ANO,"0000");
        SPINNER_ANO.setEditor(editor);

        jButton1.setText("Gerar Relatório");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Mês");

        jLabel2.setText("Ano");

        jLabel3.setText("Selecione o mês e o ano e clique em gerar relatório .");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(SPINNER_MES, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SPINNER_ANO, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(216, 216, 216))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(SPINNER_ANO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SPINNER_MES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            
            gerarPDF();
            
//
//        System.out.print("O MES SELECIONADO FOI " + SPINNER_MES.getValue() + ""
//                + " O ANO SELECIONADO FOI " + SPINNER_ANO.getValue() + "\n");
//        DatabaseConnectionMysql db_connection = new DatabaseConnectionMysql();
//        int mes_selected = (int) SPINNER_MES.getValue();
//        int ano_selected = (int) SPINNER_ANO.getValue();
//        try {
//            ResultSet resultado =     db_connection.join_registro_sisob_eturmalina(mes_selected,ano_selected);
//                
//                int i = 1;
//            while(resultado.next()){
//
//            System.out.print(resultado.getString(1) +  "  "
//            + resultado.getString(2) +  "  "
//                     + resultado.getInt(3) +  "  " 
//                    + resultado.getInt(4) +  "  "  + "\n"
//            
//            );
//           /** configurar o retorno rs para cada coluna da tabela como o 
//           **  exemplo : (rs.getInt(1)+"  "+rs.getString(2)+"  "+rs.getString(3));
//           **  pois está dando o erro
//           **  java.sql.SQLException: Invalid value for getInt() - 'MARIA IZAMI PEREIRA CAMPOS' 
//             */
//            i++;
//    
//    }
//
//        
//        } catch (SQLException ex) {
//            Logger.getLogger(TelaComparaSisobEturmalina.class.getName()).log(Level.SEVERE, null, ex);
//        }
        } catch (IOException ex) {
            Logger.getLogger(TelaComparaSisobEturmalina.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
     public void gerarPDF() throws IOException{
        /*int fontSize = 14 ;
      float leading = 1.5f * fontSize;
        try (PDDocument document = new PDDocument()) {
            document.addPage(new PDPage());
            document.save("C:\\Users\\claytonpereira\\Downloads\\relatorio.pdf");
            PDPageContentStream content = new PDPageContentStream(document,document.getPage(0));
            System.out.println("PDF created");
                  //Begin the Content stream 
      content.beginText();        
      //Setting the font to the Content stream  
      content.setFont(PDType1Font.TIMES_ROMAN, 12);
      //Setting the position for the line 
      content.newLineAtOffset(25, 500);    
      content.setLeading(14.5f);
      //Adding text in the form of string 
        String text = "This is the sample document and we are adding content to it." + "<br>"
              ;
      content.showText(text);     
      content.newLine();

      
      
      //Ending the content stream
      content.endText();

      System.out.println("Content added");

      //Closing the content stream
      content.close();
       
      document.save("C:\\Users\\claytonpereira\\Downloads\\relatorio.pdf");
        }
     
     
     **/
        
     Document  document = new Document(Constants.A4, 40, 60, 40, 60);
 
      Paragraph paragraph = new Paragraph();
        paragraph.addText("Hello Document\n", 20, PDType1Font.HELVETICA);
        document.add(paragraph);
        document.add(paragraph);
        document.add(paragraph);

 
         final OutputStream outputStream = 
          new FileOutputStream("hellodoc.pdf");
         document.save(outputStream); 
     
     
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaComparaSisobEturmalina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaComparaSisobEturmalina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaComparaSisobEturmalina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaComparaSisobEturmalina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaComparaSisobEturmalina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SPINNER_ANO;
    private javax.swing.JSpinner SPINNER_MES;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
