/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.claytonpereira.view;

import com.claytonpereira.model.Arquivo_txt_task;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.TextArea;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author claytonpereira
 */
public class TelaImportacaoSisobMensal extends javax.swing.JFrame {
public static JFileChooser selecionaarquivo; 
public static   File arquivo;
    /**
     * Creates new form TelaImportacaoSisobMensal
     */
    public TelaImportacaoSisobMensal() {
        initComponents();
        setSize(800, 600);
        salve_csv_to_db.setVisible(false);
        Converte_txt_to_csv.setVisible(false);
         setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Converte_txt_jb = new javax.swing.JButton();
        importa_csv_jb = new javax.swing.JButton();
        Converte_txt_to_csv = new java.awt.TextArea();
        salve_csv_to_db = new java.awt.TextArea();

        getContentPane().setLayout(null);

        Converte_txt_jb.setText("Converter TXT para CSV");
        Converte_txt_jb.setToolTipText("O arquivo no formato = OBI + Ano com quatro digitos + mês com dois digitos exemplo: arquivo de janeiro de 2019, ficaria assim OBI201901 . ");
        Converte_txt_jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Converte_txt_jbActionPerformed(evt);
            }
        });
        getContentPane().add(Converte_txt_jb);
        Converte_txt_jb.setBounds(10, 10, 220, 23);

        importa_csv_jb.setText("Importar Arquivo CSV Para o Banco");
        importa_csv_jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importa_csv_jbActionPerformed(evt);
            }
        });
        getContentPane().add(importa_csv_jb);
        importa_csv_jb.setBounds(10, 260, 220, 23);
        getContentPane().add(Converte_txt_to_csv);
        Converte_txt_to_csv.setBounds(10, 50, 1280, 180);
        getContentPane().add(salve_csv_to_db);
        salve_csv_to_db.setBounds(10, 290, 1280, 200);
    }// </editor-fold>//GEN-END:initComponents

     public File seleciona_arquivo( java.awt.Component tela,String desc_tipo_arquivo, String extensao,TextArea mensagem, String title) throws FileNotFoundException{
      File arquivo = null;
    
    
    
           
        selecionaarquivo  = new JFileChooser();
        selecionaarquivo.setDialogTitle(title);
        FileFilter filter = new FileNameExtensionFilter(desc_tipo_arquivo, extensao);
        selecionaarquivo.addChoosableFileFilter(filter);  
        selecionaarquivo.setAcceptAllFileFilterUsed(false);
        
        
        
        int returnVal = selecionaarquivo.showOpenDialog(tela);
        if (returnVal == JFileChooser.APPROVE_OPTION){
           
          arquivo = selecionaarquivo.getSelectedFile();
          System.out.println("abrindo: " + arquivo.getName());
        
          
        }
 if(returnVal == JFileChooser.CANCEL_OPTION){
            JOptionPane.showMessageDialog(tela, "Nenhum arquivo selecionado !");
        
        }
        
        
        
        return arquivo;
    }
    
    
    
    
    private void Converte_txt_jbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Converte_txt_jbActionPerformed
     
               Converte_txt_to_csv.setVisible(false);
       
                //arquivo = null ;
                try {
                    arquivo = seleciona_arquivo(TelaImportacaoSisobMensal.this,"arquivo Texto", "txt",Converte_txt_to_csv,"Selecione o arquivo txt do SISOB !");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(TelaImportacaoSisobMensal.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            
      
        
           Arquivo_txt_task txt = new Arquivo_txt_task();
           txt.execute();
           
       
           
        
//        try {
//          
//             
//            try {
//                txt.salvar_arquivo_txt_to_csv(arquivo,"Escolha o arquivo Csv",Converte_txt_to_csv);
//            } catch (InterruptedException ex) {
//                Logger.getLogger(TelaImportacaoSisobMensal.class.getName()).log(Level.SEVERE, null, ex);
//            }
//           
//        } catch (IOException ex) {
//            Logger.getLogger(TelaImportacaoSisobMensal.class.getName()).log(Level.SEVERE, null, ex);
//        }
//       
//                

          
      
        
    
        
        
    }//GEN-LAST:event_Converte_txt_jbActionPerformed

    private void importa_csv_jbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importa_csv_jbActionPerformed
        // TODO add your handling code here:
       salve_csv_to_db.setVisible(false);
        File arquivo = null ;
      
       // try {
            
          //  arquivo = seleciona_arquivo(this,"Arquivo CSV", "csv",salve_csv_to_db,"Selecione o arquivo csv para importar !");
//           
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(TelaImportacaoSisobMensal.class.getName()).log(Level.SEVERE, null, ex);
//        }
        Arquivo_txt_task texto = new Arquivo_txt_task();
      //  try {
           
           
//            texto.export_csv_to_db(arquivo, salve_csv_to_db);
//        } catch (SQLException ex) {
//            Logger.getLogger(TelaImportacaoSisobMensal.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IOException ex) {
//            Logger.getLogger(TelaImportacaoSisobMensal.class.getName()).log(Level.SEVERE, null, ex);

    }//GEN-LAST:event_importa_csv_jbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Converte_txt_jb;
    public static java.awt.TextArea Converte_txt_to_csv;
    public static javax.swing.JButton importa_csv_jb;
    private java.awt.TextArea salve_csv_to_db;
    // End of variables declaration//GEN-END:variables
}
